### PR TITLE
Urlencode empty dicts

### PR DESCRIPTION
**Pull request by henriquegemignani**
'if data' returns False if data is an empty dict, sending a dict down to urllib2.Request, causing an error.

### CODE REVIEW

**Comment by gaqzi** [comment]
Hi @henriquegemignani could you add a test case that fixes this issue? 
Or a code example of what is causing it so I can add a test case?

**Comment by henriquegemignani** [comment]
I encountered it by trying to unpause a paused pipeline via the gocd-cli
Em 18/08/2015 22:40, "Björn Andersson" <notifications@github.com> escreveu:

**Comment by gaqzi** [comment]
@henriquegemignani thanks! 
I managed to reproduce the same issue when I tried it out with Python 2.7. 
I don't quite understand how the original unit tests were passing under tox, but a more specific decision on how to handle values going into `post_args` is now in place so it should work more a bit more robust going forward. :)

**Comment by gaqzi** [comment]
Oh, and a new release [0.7.1](https://github.com/gaqzi/py-gocd/releases/tag/v.0.7.1) is out that takes care of this issue. 

Just a `pip install --upgrade gocd-cli` away! :)

**Comment by henriquegemignani** [comment]
Nice :)
I wanted to post a stack trace of the error, but I had to get it at work and kept forgetting to do so.
But I indeed I was using Python 2.7

**Pull request closed without merging**
